### ISSUE TITLE
502 response parse

### ISSUE THREAD

**Issue by ConnorRed** [mailshake/mailshake-node#4]
Hello,

It looks like when Mailshake returns a 502 -Bad gateway html response, we are still trying to parse the response body resulting in a “Unexpected token o in JSON at position 1” error. This usually occurs when there are multiple calls to the same API happen.

**Comment by colinmathews** [comment]
Thanks, we are looking at this right now and will implement a patch this week.

**Comment by colinmathews** [comment]
Thanks @ConnorRed for the issue. We've improved our error handling and even added some automatic error retrying for status codes >= 500. Upgrading your npm package to 1.0.6 should do the trick!
