### ISSUE TITLE
Webhook question

### ISSUE THREAD

**Issue by C-reddd** [mailshake/mailshake-node#8]
Hello,

I am working with Mailshake's webhook solution. I have a quick question: does each webhook request from Mailshake include more than one "action" object? 

For example: If you subscribe to a "sent" event and two messages are sent at the same time, are there two requests or one request with two objects in the payload?

**Comment by joshtronic** [comment]
Hey C, sorry for the delay on this. 

We don't do any batching of pushes, so each sent message would result in 1 push.

In the future, for API specific inquiries, please hit our support up, as those requests don't fall through the cracks as easily.

Cheers!
